export { default as Main } from "./Main"
export { default as CockBlock } from "./CockBlock"
export { default as Header } from "./Header"
export { default as Login } from "./Login"
export { default as Registration } from "./Registration"
export { default as Cart } from "./Cart"